### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yyhoshino** [yyhoshino/furima-38595#20]
# 自身のフリマアプリのURL
https://furima-38595.onrender.com/

# Basic認証のIDとパスワード
ID admin
PS 2222

# 出品者用のメールアドレスとパスワード
email  aaa@com
PS      1a1a1a

# 購入者用のメールアドレスとパスワード
email  bbb@com
PS      1b1b1b

**Comment by snkw-works** [comment]
@yyhoshino さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **商品出品画面、商品編集画面にて、エラーハンドリングの際、重複したエラーメッセージが表示されないよう修正しましょう**
「Price can't be blank」が重複して表示されています。
<img width="551" alt="スクリーンショット 2022-11-18 17 01 25" src="https://user-images.githubusercontent.com/54050089/202651259-d04a2296-15df-477b-953e-f79b9e392d37.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by yyhoshino** [comment]
ご確認ありがとうございます！
修正したら、再度gitで
コミット→プッシュ→プルリクエストの作成→マージ→デプロイ→挙動確認依頼の手順でよろしいですか？

**Comment by yyhoshino** [comment]
ご確認ありがとうございました！今後も精進して参ります！
